export type Service = {
  slug: string;
  family: string;
  title: string;
  tagline: string;
  intro: string;
  whenUseful: string[];
  capabilities: { title: string; body: string }[];
  deliverables: string[];
  approach: string[];
  faqs: { q: string; a: string }[];
  seo: { title: string; description: string };
};

const baseFaq = (title: string): { q: string; a: string }[] => [
  { q: `How do we start a ${title.toLowerCase()} engagement?`, a: "We begin with a short discovery call to understand the business goal, constraints, and the smallest credible engagement. From there we propose a scope, timeline, and team shape." },
  { q: "Who owns the code, accounts, and documentation?", a: "You do. Ownership transfer is part of delivery, not an afterthought. We document architecture, decisions, and operating playbooks throughout the engagement." },
  { q: "How do you handle change requests during a project?", a: "We work in visible increments and make trade-offs explicit. Changes are scoped, prioritised against existing outcomes, and agreed before they affect the plan." },
];

export const SERVICES: Service[] = [
  {
    slug: "ai-and-automation",
    family: "AI & Intelligent Systems",
    title: "AI & Automation",
    tagline: "Turn repetitive work and fragmented knowledge into intelligent, controlled workflows.",
    intro: "We use AI to remove friction from operations, decisions, and customer experience — without surrendering judgment, security, or code quality.",
    whenUseful: [
      "Teams spend hours on repetitive lookups, summaries, or hand-offs.",
      "Knowledge is locked in documents, tickets, or email threads.",
      "You want measurable leverage from AI, not a press release.",
    ],
    capabilities: [
      { title: "Workflow automation", body: "Identify the highest-leverage workflows, then automate the steps that benefit from machine speed and consistency." },
      { title: "Retrieval systems", body: "Make your own knowledge usable: clean ingestion, structured retrieval, evaluation, and observability." },
      { title: "Decision support", body: "Surface the right context at the right step so humans make better decisions, faster." },
      { title: "Evaluation and monitoring", body: "Continuous evaluation of accuracy, cost, latency, and drift — not a one-off launch." },
    ],
    approach: [
      "Map the workflow and define the smallest valuable release.",
      "Choose models, tools, and guardrails appropriate to the risk.",
      "Ship behind a feature flag with evaluation in place.",
      "Iterate based on real usage and operating cost.",
    ],
    deliverables: ["Workflow map and success signals", "Working automation in production", "Evaluation harness and dashboards", "Operating playbook and ownership transfer"],
    faqs: baseFaq("AI & Automation"),
    seo: { title: "AI & Automation Services | CodersDive", description: "Automate repetitive work and unlock fragmented knowledge with controlled, evaluated AI workflows engineered by CodersDive." },
  },
  {
    slug: "ai-agents",
    family: "AI & Intelligent Systems",
    title: "AI Agents",
    tagline: "Agents that reason, use tools, retrieve context, and complete bounded business tasks.",
    intro: "We design agents the way we design products — with explicit scope, observability, and human accountability built in.",
    whenUseful: [
      "You have a repeating task that crosses systems and requires judgment.",
      "Existing automation breaks on edge cases or unstructured input.",
      "You need an agent with clear tool access and audit trails.",
    ],
    capabilities: [
      { title: "Task and tool design", body: "Define what the agent can and cannot do, with explicit boundaries and approval steps." },
      { title: "Retrieval and memory", body: "Give the agent the context it needs without leaking what it should not see." },
      { title: "Observability", body: "Trace every decision, tool call, and cost so operations stay accountable." },
      { title: "Evaluation", body: "Continuous regression tests on real cases — not curated demos." },
    ],
    approach: [
      "Scope a single bounded task with measurable success.",
      "Choose model, tools, and guardrails for that task.",
      "Instrument tracing and human-in-the-loop where it matters.",
      "Expand scope only after the bounded case is reliable.",
    ],
    deliverables: ["Agent specification with explicit boundaries", "Production agent with observability", "Evaluation suite and operating playbook"],
    faqs: baseFaq("AI Agents"),
    seo: { title: "AI Agent Development | CodersDive", description: "Bounded, observable AI agents that complete real business tasks — engineered with guardrails, evaluation, and human accountability." },
  },
  {
    slug: "generative-ai-applications",
    family: "AI & Intelligent Systems",
    title: "Generative AI Applications",
    tagline: "Useful AI experiences grounded in your data, workflow, and product constraints.",
    intro: "Beyond demos: we build generative features that integrate with real products and pass real evaluation.",
    whenUseful: ["You want AI inside an existing product, not a side experiment.", "You need control over cost, latency, and accuracy.", "You need an experience users trust."],
    capabilities: [
      { title: "Product integration", body: "Embed generative features inside existing interfaces without breaking workflow." },
      { title: "Grounding and retrieval", body: "Connect models to your real data with proper retrieval, citations, and freshness." },
      { title: "Model evaluation", body: "Compare models and prompts against your own success criteria." },
      { title: "Cost and latency control", body: "Right-size models, caching, and routing for predictable economics." },
    ],
    approach: ["Pick a feature with clear value.", "Prototype with two model paths.", "Evaluate, instrument, ship.", "Iterate against real usage."],
    deliverables: ["Working AI feature in production", "Evaluation harness", "Cost and latency dashboard"],
    faqs: baseFaq("Generative AI Applications"),
    seo: { title: "Generative AI Application Development | CodersDive", description: "Generative AI features grounded in your data, evaluated against real criteria, and engineered for predictable cost and latency." },
  },
  {
    slug: "custom-software-development",
    family: "Product Engineering",
    title: "Custom Software Development",
    tagline: "Replace awkward workarounds with software designed around the way your business actually operates.",
    intro: "When off-the-shelf software no longer fits, we design and build custom systems that honour your real workflow.",
    whenUseful: ["Spreadsheets and SaaS hand-offs are causing errors.", "An internal tool needs to scale beyond its prototype.", "Off-the-shelf software forces you to operate against your own model."],
    capabilities: [
      { title: "Internal tools and back-office", body: "Replace fragile spreadsheets and tickets with software designed around the real operating model." },
      { title: "Complex integrations", body: "Connect ERPs, CRMs, payment systems, and legacy databases reliably." },
      { title: "Business workflow systems", body: "Approvals, queues, exceptions, audit trails — modelled correctly." },
      { title: "Reporting and analytics", body: "Operating data turned into decisions, not dashboards no one opens." },
    ],
    approach: ["Map the real workflow, including exceptions.", "Define the smallest valuable release.", "Build in tested increments.", "Document operating model and hand over."],
    deliverables: ["Production system with documentation", "Test suite and CI/CD", "Operating playbook"],
    faqs: baseFaq("Custom Software"),
    seo: { title: "Custom Software Development | CodersDive", description: "Custom internal tools, workflow systems, and back-office software built around how your business really operates." },
  },
  {
    slug: "saas-product-development",
    family: "Product Engineering",
    title: "SaaS Product Development",
    tagline: "Move from validated problem to reliable subscription product with a product-minded engineering team.",
    intro: "We help founders and product leaders ship SaaS that retains, expands, and is affordable to operate.",
    whenUseful: ["You have validated demand and need to ship a real product.", "Your current SaaS is fragile or expensive to operate.", "You need product, design, and engineering in one accountable team."],
    capabilities: [
      { title: "Multi-tenant architecture", body: "Tenancy, billing, and roles done properly from day one." },
      { title: "Onboarding and activation", body: "Flows designed for retention, not just signups." },
      { title: "Billing and metering", body: "Stripe, usage-based pricing, plan changes, dunning." },
      { title: "Operations and reliability", body: "Observability, support tooling, and runbooks." },
    ],
    approach: ["Define the activation moment.", "Ship a credible MVP with paying users.", "Instrument retention and cost.", "Iterate against real cohorts."],
    deliverables: ["Production SaaS with billing", "Onboarding and activation flows", "Reliability and observability"],
    faqs: baseFaq("SaaS Product Development"),
    seo: { title: "SaaS Product Development | CodersDive", description: "Engineer a subscription product that retains, expands, and is affordable to operate — with a product-minded team." },
  },
  {
    slug: "web-application-development",
    family: "Product Engineering",
    title: "Web Application Development",
    tagline: "Fast, accessible, scalable web applications that feel effortless to use.",
    intro: "Modern web apps engineered for performance, accessibility, and long-term maintainability.",
    whenUseful: ["You need a high-quality public or authenticated web app.", "Performance and accessibility actually matter.", "Your team will own and evolve the code."],
    capabilities: [
      { title: "Application architecture", body: "Sensible defaults, type safety, and clear boundaries." },
      { title: "Performance optimization", body: "Core Web Vitals as a deliverable, not an afterthought." },
      { title: "Accessibility", body: "WCAG-conscious design and implementation." },
      { title: "Authenticated experiences", body: "Auth, roles, multi-tenant data, and audit trails." },
    ],
    approach: ["Scope the experience, not just the pages.", "Build with measured performance budgets.", "Ship with monitoring.", "Iterate from real data."],
    deliverables: ["Production web application", "Performance and a11y reports", "CI/CD and observability"],
    faqs: baseFaq("Web Applications"),
    seo: { title: "Web Application Development | CodersDive", description: "High-performance, accessible web applications engineered for real users and long-term maintainability." },
  },
  {
    slug: "mobile-app-development",
    family: "Product Engineering",
    title: "Mobile App Development",
    tagline: "Mobile products that feel native, resilient, and aligned with real user behaviour.",
    intro: "iOS, Android, and cross-platform mobile engineering with offline-first, performance, and store-readiness built in.",
    whenUseful: ["You need a mobile experience users keep open.", "Offline, sync, or hardware features matter.", "You need a credible release pipeline."],
    capabilities: [
      { title: "Native and cross-platform", body: "React Native, Swift, Kotlin — chosen for the product, not the trend." },
      { title: "Offline and sync", body: "Local-first patterns where bandwidth and reliability matter." },
      { title: "App store readiness", body: "Submission, review, and operations playbook." },
      { title: "Performance and telemetry", body: "Real device data, not emulator promises." },
    ],
    approach: ["Decide on platform strategy.", "Prototype the critical flow.", "Ship to TestFlight / internal track.", "Iterate, then release."],
    deliverables: ["Production mobile app", "Store submission and review", "Telemetry and crash reporting"],
    faqs: baseFaq("Mobile Apps"),
    seo: { title: "Mobile App Development | CodersDive", description: "Native and cross-platform mobile apps engineered for real users, offline resilience, and store readiness." },
  },
  {
    slug: "e-commerce-development",
    family: "Product Engineering",
    title: "E-commerce Development",
    tagline: "Storefronts and commerce systems that reduce friction from discovery to repeat purchase.",
    intro: "From headless Shopify to custom commerce, we build storefronts that convert and back-office systems that scale.",
    whenUseful: ["Conversion is below where it should be.", "Operations are buckling under order volume.", "You need a headless or composable architecture."],
    capabilities: [
      { title: "Headless commerce", body: "Shopify Hydrogen, custom storefronts, and composable backends." },
      { title: "Operations integrations", body: "ERP, WMS, 3PL, and finance systems wired correctly." },
      { title: "Performance and SEO", body: "Storefronts that load fast and rank." },
      { title: "Loyalty and lifecycle", body: "Subscriptions, retention, and post-purchase experiences." },
    ],
    approach: ["Audit conversion and operations.", "Choose platform direction.", "Ship the storefront and back-office in increments.", "Iterate on conversion and operations."],
    deliverables: ["Production storefront", "Back-office integrations", "Analytics and experimentation setup"],
    faqs: baseFaq("E-commerce"),
    seo: { title: "E-commerce Development | CodersDive", description: "Headless and custom commerce engineered for conversion, operations, and lifecycle revenue." },
  },
  {
    slug: "ui-ux-product-design",
    family: "Experience",
    title: "UI/UX & Product Design",
    tagline: "Clarify the product, remove friction, and create interfaces users understand without a manual.",
    intro: "Product design that starts with the user decision, not the screen.",
    whenUseful: ["Users get lost in your product.", "Your team disagrees on the right experience.", "You need a design system, not one-off screens."],
    capabilities: [
      { title: "Research and discovery", body: "Talk to real users; map real decisions." },
      { title: "Interaction design", body: "Flows, states, and edge cases — not pretty screens." },
      { title: "Interface and system design", body: "A scalable visual system that engineering can build with." },
      { title: "Prototyping", body: "Test the riskiest interaction before it is expensive." },
    ],
    approach: ["Frame the user decision.", "Prototype and test.", "Design the system, not the page.", "Hand off with engineering in the room."],
    deliverables: ["User research notes", "Interactive prototypes", "Production-ready design system"],
    faqs: baseFaq("Product Design"),
    seo: { title: "UI/UX & Product Design | CodersDive", description: "Product design that clarifies decisions, removes friction, and gives engineering a system to build with." },
  },
  {
    slug: "mvp-proof-of-concept",
    family: "Experience",
    title: "MVP & Proof of Concept",
    tagline: "Validate the riskiest assumption quickly without creating a throwaway product.",
    intro: "An MVP is not a smaller version of the final product — it is the cheapest experiment that resolves the riskiest unknown.",
    whenUseful: ["You need investor or executive confidence.", "You are unsure which assumption to test first.", "You want a real product, not a prototype, but cheap."],
    capabilities: [
      { title: "Assumption mapping", body: "Identify what must be true for the product to work." },
      { title: "Rapid prototyping", body: "Prototype the risky path, not the trivial one." },
      { title: "Production-credible MVP", body: "A small product real users can use today." },
      { title: "Launch learning plan", body: "What you will measure and how you will decide what is next." },
    ],
    approach: ["Frame the riskiest assumption.", "Choose the cheapest credible test.", "Ship in 4–8 weeks.", "Decide what is next from real signal."],
    deliverables: ["MVP in production", "Learning plan and instrumentation", "Decision memo with next-step options"],
    faqs: baseFaq("MVP & PoC"),
    seo: { title: "MVP & Proof of Concept Development | CodersDive", description: "Resolve your riskiest assumption with a production-credible MVP — shipped fast, instrumented to learn." },
  },
  {
    slug: "cloud-devops",
    family: "Platforms & Reliability",
    title: "Cloud & DevOps",
    tagline: "Secure, repeatable delivery systems that let teams ship without deployment drama.",
    intro: "Infrastructure-as-code, observability, and pipelines designed for the team that has to live with them.",
    whenUseful: ["Deployments feel risky or take all day.", "You cannot tell what broke when it breaks.", "Cloud costs are increasing without explanation."],
    capabilities: [
      { title: "Cloud architecture", body: "AWS, GCP, or Azure designed for cost and clarity." },
      { title: "CI/CD and continuous delivery", body: "Confidence to ship multiple times a day." },
      { title: "Observability", body: "Tracing, metrics, and logs that engineers actually use." },
      { title: "Cost optimisation", body: "Spend you understand and can act on." },
    ],
    approach: ["Audit the current pipeline and infrastructure.", "Stabilise the riskiest weakness first.", "Improve in measured increments.", "Document and hand over."],
    deliverables: ["Modern pipeline and infrastructure", "Observability dashboards", "Runbooks and on-call documentation"],
    faqs: baseFaq("Cloud & DevOps"),
    seo: { title: "Cloud & DevOps Services | CodersDive", description: "Repeatable cloud infrastructure, CI/CD, and observability for teams that need to ship without deployment drama." },
  },
  {
    slug: "legacy-modernization",
    family: "Platforms & Reliability",
    title: "Legacy Modernization",
    tagline: "Modernize critical software in controlled steps while protecting business continuity.",
    intro: "Modernisation that prioritises the business — not a rewrite for its own sake.",
    whenUseful: ["A critical system is slowing the business down.", "Knowledge is concentrated in one or two people.", "A rewrite has been attempted and abandoned before."],
    capabilities: [
      { title: "Assessment", body: "What is salvageable, what is risky, what to replace first." },
      { title: "Incremental modernisation", body: "Strangler-fig patterns, not big-bang rewrites." },
      { title: "Data migration", body: "Move data without losing trust or history." },
      { title: "Knowledge capture", body: "Make tacit knowledge explicit." },
    ],
    approach: ["Assess current system and risks.", "Choose the smallest valuable modernisation.", "Migrate in controlled steps.", "Document throughout."],
    deliverables: ["Modernisation roadmap", "Incremental migrations", "Documentation and tests"],
    faqs: baseFaq("Legacy Modernization"),
    seo: { title: "Legacy Software Modernization | CodersDive", description: "Controlled, business-safe modernisation of critical software using incremental strangler-fig patterns." },
  },
  {
    slug: "api-systems-integration",
    family: "Platforms & Reliability",
    title: "API & Systems Integration",
    tagline: "Connect the tools your business depends on so data and work move without manual re-entry.",
    intro: "Integration done as a product, not as duct tape.",
    whenUseful: ["Your team re-enters the same data across systems.", "Reports do not reconcile.", "A new tool needs to fit a complex landscape."],
    capabilities: [
      { title: "API design", body: "Clean, versioned, documented APIs others can build with." },
      { title: "Integration platforms", body: "Webhooks, queues, ETL/ELT — the right pattern for the job." },
      { title: "Identity and data flow", body: "SSO, RBAC, and reliable data movement." },
      { title: "Observability", body: "When integrations break, you know first." },
    ],
    approach: ["Map the systems and contracts.", "Choose the right integration pattern.", "Build with monitoring and replay.", "Document the data flow."],
    deliverables: ["Reliable integrations", "API documentation", "Monitoring and replay tooling"],
    faqs: baseFaq("API & Integration"),
    seo: { title: "API & Systems Integration | CodersDive", description: "Reliable, observable integrations between the systems your business depends on — built as a product." },
  },
  {
    slug: "qa-testing",
    family: "Platforms & Reliability",
    title: "Quality Assurance & Testing",
    tagline: "Build confidence into every release through practical test strategy and automation.",
    intro: "Quality is a delivery practice, not a phase at the end.",
    whenUseful: ["Releases feel risky.", "Regressions are caught by users.", "Engineering velocity is slowing under unknown technical debt."],
    capabilities: [
      { title: "Test strategy", body: "What to test, where, and how — proportional to risk." },
      { title: "Automation", body: "Unit, integration, end-to-end, and visual." },
      { title: "Performance testing", body: "Find the breaking point before users do." },
      { title: "Release management", body: "Feature flags, canaries, and roll-back paths." },
    ],
    approach: ["Assess current quality and risks.", "Define a proportional test strategy.", "Automate the highest-value tests.", "Embed quality in the team."],
    deliverables: ["Test strategy document", "Automated test suites", "Release management playbook"],
    faqs: baseFaq("QA & Testing"),
    seo: { title: "QA & Testing Services | CodersDive", description: "Practical, risk-proportional test strategy and automation that gives engineering teams confidence to ship." },
  },
  {
    slug: "dedicated-product-teams",
    family: "Partnership",
    title: "Dedicated Product Teams",
    tagline: "Add a stable cross-functional team that learns your product and ships continuously.",
    intro: "A pod of product, design, and engineering that operates as part of your team.",
    whenUseful: ["You need continuous capacity, not project bursts.", "Your roadmap is too large for the team you have.", "You want product thinking, not staff augmentation."],
    capabilities: [
      { title: "Cross-functional pod", body: "Product, design, engineering, QA — together." },
      { title: "Continuous delivery", body: "Predictable, visible delivery cadence." },
      { title: "Roadmap partnership", body: "Help shape priorities, not just execute them." },
      { title: "Long-term ownership", body: "Built-in continuity and knowledge transfer." },
    ],
    approach: ["Shape the pod for the work.", "Onboard into your product and team.", "Operate at a predictable cadence.", "Adjust composition as priorities shift."],
    deliverables: ["Embedded pod operating against your roadmap", "Continuous delivery cadence", "Documentation and continuity plan"],
    faqs: baseFaq("Dedicated Product Teams"),
    seo: { title: "Dedicated Product Teams | CodersDive", description: "A stable, cross-functional pod that learns your product and ships continuously — product thinking included." },
  },
  {
    slug: "support-continuous-improvement",
    family: "Partnership",
    title: "Support & Continuous Improvement",
    tagline: "Keep software secure, stable, and improving after launch.",
    intro: "Launch is the start of learning, not the end of responsibility.",
    whenUseful: ["A product is live and needs accountable care.", "You need a measured response to incidents.", "You want continuous improvement, not stagnation."],
    capabilities: [
      { title: "Operational support", body: "SLAs, on-call, and incident response that match the product." },
      { title: "Security and patching", body: "Stay current on dependencies and posture." },
      { title: "Performance and cost", body: "Continuous tuning of speed and spend." },
      { title: "Continuous improvement", body: "Small, regular product improvements based on real usage." },
    ],
    approach: ["Define the service shape.", "Establish observability and on-call.", "Operate with a regular improvement cadence.", "Report on outcomes, not tickets."],
    deliverables: ["Operating service with SLAs", "Continuous improvement backlog", "Quarterly review and roadmap"],
    faqs: baseFaq("Support & Continuous Improvement"),
    seo: { title: "Software Support & Continuous Improvement | CodersDive", description: "Accountable post-launch support, security, performance, and continuous improvement for production software." },
  },
];

export const SERVICE_FAMILIES = Array.from(new Set(SERVICES.map((s) => s.family)));
export const getService = (slug: string) => SERVICES.find((s) => s.slug === slug);